default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432

production: &production
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>

staging:
  <<: *production

training:
  <<: *production

development:
  <<: *default
  database: portoseguro_development
  min_messages: warning
  username: postgres
  password: postgres

test:
  <<: *default
  database: portoseguro_test
  min_messages: warning
  username: postgres
  password: postgres
