development:
  adapter: postgresql
  encoding: unicode
  database: tributario_development
  pool: 5
  min_messages: warning
  username: tributario
  password: tributario

test:
  adapter: postgresql
  encoding: unicode
  database: tributario_test
  pool: 5
  min_messages: warning
  username: tributario
  password: tributario
