default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

production: &production
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>

staging:
  <<: *production

training:
  <<: *production

development:
  <<: *default
  database: compras_development
  min_messages: warning
  username: compras
  password: compras

test:
  <<: *default
  database: compras_test
  min_messages: warning
  username: compras
  password: compras
