development:
  adapter: postgresql
  encoding: unicode
  database: compras_development
  pool: 5
  min_messages: warning
  username: compras
  password: compras

test:
  adapter: postgresql
  encoding: unicode
  database: compras_test
  pool: 5
  min_messages: warning
  username: compras
  password: compras
