class AddingComprasPrefixToTables < ActiveRecord::Migration
  def change
    rename_table :accredited_representatives, :compras_accredited_representatives
    rename_table :administration_types, :compras_administration_types
    rename_table :administrative_processes, :compras_administrative_processes
    rename_table :administrative_process_budget_allocations, :compras_administrative_process_budget_allocations
    rename_table :administrative_process_budget_allocation_items, :compras_administrative_process_budget_allocation_items
    rename_table :agencies, :compras_agencies
    rename_table :banks, :compras_banks
    rename_table :bank_accounts, :compras_bank_accounts
    rename_table :bookmarks, :compras_bookmarks
    rename_table :bookmarks_links, :compras_bookmarks_links
    rename_table :budget_allocations, :compras_budget_allocations
    rename_table :budget_allocation_types, :compras_budget_allocation_types
    rename_table :budget_structures, :compras_budget_structures
    rename_table :budget_structure_configurations, :compras_budget_structure_configurations
    rename_table :budget_structure_levels, :compras_budget_structure_levels
    rename_table :budget_structure_responsibles, :compras_budget_structure_responsibles
    rename_table :capabilities, :compras_capabilities
    rename_table :cnaes, :compras_cnaes
    rename_table :communication_sources, :compras_communication_sources
    rename_table :companies, :compras_companies
    rename_table :contracts, :compras_contracts
    rename_table :creditors, :compras_creditors
    rename_table :creditor_balances, :compras_creditor_balances
    rename_table :creditor_bank_accounts, :compras_creditor_bank_accounts
    rename_table :creditor_documents, :compras_creditor_documents
    rename_table :creditor_materials, :compras_creditor_materials
    rename_table :creditor_representatives, :compras_creditor_representatives
    rename_table :creditor_secondary_cnaes, :compras_creditor_secondary_cnaes
    rename_table :currencies, :compras_currencies
    rename_table :customers, :compras_customers
    rename_table :delivery_locations, :compras_delivery_locations
    rename_table :direct_purchases, :compras_direct_purchases
    rename_table :direct_purchase_budget_allocations, :compras_direct_purchase_budget_allocations
    rename_table :direct_purchase_budget_allocation_items, :compras_direct_purchase_budget_allocation_items
    rename_table :dissemination_sources, :compras_dissemination_sources
    rename_table :dissemination_sources_regulatory_acts, :compras_dissemination_sources_regulatory_acts
    rename_table :document_types, :compras_document_types
    rename_table :document_types_licitation_processes, :compras_document_types_licitation_processes
    rename_table :economic_registrations, :compras_economic_registrations
    rename_table :employees, :compras_employees
    rename_table :entities, :compras_entities
    rename_table :expense_categories, :compras_expense_categories
    rename_table :expense_elements, :compras_expense_elements
    rename_table :expense_groups, :compras_expense_groups
    rename_table :expense_kinds, :compras_expense_kinds
    rename_table :expense_modalities, :compras_expense_modalities
    rename_table :expense_natures, :compras_expense_natures
    rename_table :extra_credits, :compras_extra_credits
    rename_table :extra_credit_moviment_types, :compras_extra_credit_moviment_types
    rename_table :extra_credit_natures, :compras_extra_credit_natures
    rename_table :fiscal_years, :compras_fiscal_years
    rename_table :functions, :compras_functions
    rename_table :government_actions, :compras_government_actions
    rename_table :government_programs, :compras_government_programs
    rename_table :identities, :compras_identities
    rename_table :indexers, :compras_indexers
    rename_table :indexer_values, :compras_indexer_values
    rename_table :individuals, :compras_individuals
    rename_table :judgment_commission_advices, :compras_judgment_commission_advices
    rename_table :judgment_commission_advice_members, :compras_judgment_commission_advice_members
    rename_table :judgment_forms, :compras_judgment_forms
    rename_table :legal_references, :compras_legal_references
    rename_table :legal_text_natures, :compras_legal_text_natures
    rename_table :licitation_commissions, :compras_licitation_commissions
    rename_table :licitation_commission_members, :compras_licitation_commission_members
    rename_table :licitation_commission_responsibles, :compras_licitation_commission_responsibles
    rename_table :licitation_modalities, :compras_licitation_modalities
    rename_table :licitation_notices, :compras_licitation_notices
    rename_table :licitation_objects, :compras_licitation_objects
    rename_table :licitation_objects_materials, :compras_licitation_objects_materials
    rename_table :licitation_processes, :compras_licitation_processes
    rename_table :licitation_process_appeals, :compras_licitation_process_appeals
    rename_table :licitation_process_bidders, :compras_licitation_process_bidders
    rename_table :licitation_process_bidder_documents, :compras_licitation_process_bidder_documents
    rename_table :licitation_process_bidder_proposals, :compras_licitation_process_bidder_proposals
    rename_table :licitation_process_impugnments, :compras_licitation_process_impugnments
    rename_table :licitation_process_lots, :compras_licitation_process_lots
    rename_table :licitation_process_publications, :compras_licitation_process_publications
    rename_table :links, :compras_links
    rename_table :management_units, :compras_management_units
    rename_table :materials, :compras_materials
    rename_table :materials_classes, :compras_materials_classes
    rename_table :materials_groups, :compras_materials_groups
    rename_table :materials_providers, :compras_materials_providers
    rename_table :materials_classes_providers, :compras_materials_classes_providers
    rename_table :materials_groups_providers, :compras_materials_groups_providers
    rename_table :modality_limits, :compras_modality_limits
    rename_table :moviment_types, :compras_moviment_types
    rename_table :occupation_classifications, :compras_occupation_classifications
    rename_table :partners, :compras_partners
    rename_table :payment_methods, :compras_payment_methods
    rename_table :people, :compras_people
    rename_table :pledges, :compras_pledges
    rename_table :pledge_cancellations, :compras_pledge_cancellations
    rename_table :pledge_categories, :compras_pledge_categories
    rename_table :pledge_historics, :compras_pledge_historics
    rename_table :pledge_items, :compras_pledge_items
    rename_table :pledge_liquidations, :compras_pledge_liquidations
    rename_table :pledge_liquidation_cancellations, :compras_pledge_liquidation_cancellations
    rename_table :pledge_parcels, :compras_pledge_parcels
    rename_table :pledge_parcel_movimentations, :compras_pledge_parcel_movimentations
    rename_table :positions, :compras_positions
    rename_table :precatories, :compras_precatories
    rename_table :precatory_parcels, :compras_precatory_parcels
    rename_table :precatory_types, :compras_precatory_types
    rename_table :prefectures, :compras_prefectures
    rename_table :price_collections, :compras_price_collections
    rename_table :price_collection_annuls, :compras_price_collection_annuls
    rename_table :price_collection_lots, :compras_price_collection_lots
    rename_table :price_collection_lot_items, :compras_price_collection_lot_items
    rename_table :price_collection_proposals, :compras_price_collection_proposals
    rename_table :price_collection_proposal_items, :compras_price_collection_proposal_items
    rename_table :providers, :compras_providers
    rename_table :profiles, :compras_profiles
    rename_table :provider_licitation_documents, :compras_provider_licitation_documents
    rename_table :provider_partners, :compras_provider_partners
    rename_table :purchase_solicitations, :compras_purchase_solicitations
    rename_table :purchase_solicitation_budget_allocations, :compras_purchase_solicitation_budget_allocations
    rename_table :purchase_solicitation_budget_allocation_items, :compras_purchase_solicitation_budget_allocation_items
    rename_table :reference_units, :compras_reference_units
    rename_table :registration_cadastral_certificates, :compras_registration_cadastral_certificates
    rename_table :regularization_or_administrative_sanction_reasons, :compras_regularization_or_administrative_sanction_reasons
    rename_table :regularization_or_administrative_sanctions, :compras_regularization_or_administrative_sanctions
    rename_table :regulatory_acts, :compras_regulatory_acts
    rename_table :regulatory_act_types, :compras_regulatory_act_types
    rename_table :regulatory_act_type_classifications, :compras_regulatory_act_type_classifications
    rename_table :reserve_allocation_types, :compras_reserve_allocation_types
    rename_table :reserve_funds, :compras_reserve_funds
    rename_table :resource_annuls, :compras_resource_annuls
    rename_table :revenue_accountings, :compras_revenue_accountings
    rename_table :revenue_categories, :compras_revenue_categories
    rename_table :revenue_natures, :compras_revenue_natures
    rename_table :revenue_rubrics, :compras_revenue_rubrics
    rename_table :revenue_sources, :compras_revenue_sources
    rename_table :revenue_subcategories, :compras_revenue_subcategories
    rename_table :risk_degrees, :compras_risk_degrees
    rename_table :roles, :compras_roles
    rename_table :service_or_contract_types, :compras_service_or_contract_types
    rename_table :settings, :compras_settings
    rename_table :signatures, :compras_signatures
    rename_table :signature_configurations, :compras_signature_configurations
    rename_table :signature_configuration_items, :compras_signature_configuration_items
    rename_table :special_entries, :compras_special_entries
    rename_table :subfunctions, :compras_subfunctions
    rename_table :supply_authorizations, :compras_supply_authorizations
    rename_table :users, :compras_users
  end
end
