class RenameColumnPurchaseSolicitatiobudgetAllocationEconomicClassificationOfExpenditureIdToExpenseEconomicClassificationId < ActiveRecord::Migration
  def change
    rename_column :purchase_solicitation_budget_allocations, :economic_classification_of_expenditure_id, :expense_economic_classification_id
  end
end
