class Report::PurchaseProcessRatificationsByPeriodsController < Report::BaseController
  report_class PurchaseProcessRatificationsByPeriodReport, :repository => PurchaseProcessRatificationsByPeriodSearcher
end
